#!/bin/bash
# Use this as a run script with daemontools or runit

## ABSOLUTE path to the spawn-fcgi binary
SPAWNFCGI="/usr/bin/spawn-fcgi"

## ABSOLUTE path to the multiwatch binary
MULTIWATCH="/usr/bin/multiwatch"

## ABSOLUTE path to the FastCGI application (php-cgi, dispatch.fcgi, ...)
FCGIPROGRAM="/usr/local/bin/#{PROJECT_NAME}-#{JOINED_WSAPI}.fcgi"

## bind to unix socket
FCGISOCKET="/tmp/#{PROJECT_NAME}-#{JOINED_WSAPI}.socket"

## Number of forks
FCGI_CHILDREN=10

## if this script is run as root switch to the following user
USERID=www-data
SOCKUSERID=www-data

################## no config below this line

exec 2>&1

ALLOWED_ENV=""

EX="$SPAWNFCGI -n -s $FCGISOCKET -u $USERID -U $SOCKUSERID -- $MULTIWATCH -f $FCGI_CHILDREN $FCGIPROGRAM"

# copy the allowed environment variables
E=

for i in $ALLOWED_ENV; do
  E="$E $i=${!i}"
done

# clean environment and set up a new one
exec env - $E $EX
